apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudpose-deploy
  labels:
    app: cloudpose
spec:
  replicas: 1          
  selector:
    matchLabels:
      app: cloudpose11-api
  template:
    metadata:
      labels:
        app: cloudpose11-api
    spec:
      containers:
      - name: cloudpose11-container
        image: nryreddy/cloudpose11-api:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 60000
        resources:
          requests:
            cpu: "500m"         # 0.5 CPU
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1000Mi"
        env:                    
        - name: UVICORN_HOST
          value: "0.0.0.0"
        - name: UVICORN_PORT
          value: "60000"
        
        livenessProbe:
          httpGet:
            path: /docs
            port: 60000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /docs
            port: 60000
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: cloudpose-svc
spec:
  type: NodePort
  selector:
    app: cloudpose11-api
  ports:
  - port: 60000            # cluster-internal port
    targetPort: 60000      # container port
    nodePort: 30003        # external <VM-IP>:30003